import { Inter } from "next/font/google";
import Layout from "@/components/layout";
import Link from "next/link";
import { API_KEY, BASE_PATH, BASE_URL } from "@/lib/constant";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ movies }) {
  return (
    <>
      <Layout>
        <Head>
          <title>Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
            crossorigin="anonymous"
          ></link>
        </Head>
        <div className="container mt-4">
          <div className="row g-3">
            {movies.results.map((movie) => (
              <div className="col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2 col-xxl-3">
                <Link
                  href={{
                    pathname: `/movies/${movie.id}`,
                    query: {
                      movie: JSON.stringify(movie),
                    },
                  }}
                  as={`/movies/${movie.id}`}
                  className="text-decoration-none"
                >
                  <div className="card border-0 shadow-sm h-100">
                    <img
                      src={BASE_PATH + movie.backdrop_path}
                      className="card-img-top"
                      alt="..."
                    />
                    <div className="card-body">
                      <p className="card-text">{movie.title}</p>

                      <button type="button" class="btn btn-primary">
                        View detail
                      </button>
                    </div>
                  </div>
                </Link>
              </div>
            ))}
          </div>
        </div>
      </Layout>
    </>
  );
}
export async function getServerSideProps() {
  console.log(`${BASE_URL}/movie/popular?api_key=${API_KEY}&page=1`);
  const res = await fetch(
    `${BASE_URL}/movie/popular?api_key=${API_KEY}&page=1`
  );
  const movies = await res.json();
  console.log(movies);

  return {
    props: {
      movies: movies,
    }, //will be passed to the page component as props
  };
}
